### PR TITLE
Modernize neovis.js and added a version without bundled vendors

### PR DESCRIPTION
**Pull request by thebestnom**
added eslint (used tabs instead of spaces, I prefer it that way, but if you want I can config it to use 4 spaces)
added babel
added console.log debug flag
implemented reinit
fixed sizeCypher
removed vendor and added them as dependencies in package json
added neovis version that comes build without bundling dependencies

and lastly modernized the js!

I want to remove css so you wouldnt need to add rule to your webpack if you are using the version without bundled dependencies

### CODE REVIEW

**Comment by thebestnom** [comment]
@johnymontana I started using neovis and I needed to add some features, 
I saw that neovis is writen in very old js stack so I decided to update it so I can more easily add feature.
I want for the next feature to add click event per node label and edge type and I will make it as soon as you merge this request,
I dont care manging this repo if you dont have time

**Comment by thebestnom** [comment]
@neo4j-contrib someone still managing this repo?

**Comment by thebestnom** [comment]
I was told by michael in slack to ping you @johnymontana

**Comment by thebestnom** [comment]
By the way, I made sizeCypher "sync", but what you did there with addNode was a bug, and if you wanted it to work you needed to do was to use _data.node.update, which wouldnt work reliably because you make the dataset only after everything was working, so I made it "sync" so it will feel a littlle bit slower with sizeCypher, but at least it will work

**Comment by johnymontana** [comment]
Thanks @thebestnom! Looks good

**Pull request merged**
