### PR TITLE
Extended the abilities to provide data to neovis

### PR DESCRIPTION
**Pull request by jexp**
- pass a bolt driver instead of connection details
- pass statement result records
- pass graph data directly

also updated readme with docs and added example html files

### CODE REVIEW

**Comment by jexp** [comment]
One thing I'd like to discuss quickly.

Currently passing in the graph data directly exposes the internal properties like `value, label, group`.

It might be nicer for external users to just pass their graph-data as-is and still use the mapping config.

WDYT?

**Comment by johnymontana** [comment]
Thanks for the PR. With the "graph data" approach there are a few things that might break (for example node size can be bound to a Cypher query, and we allow for node labels to be used as captions, depending on config). 

So maybe some sort of config validation approach should be considered to validate any user provided data. But I'm OK with merging this in now and figuring that out later.

**Comment by chriszirkel** [comment]
This sounds promising! The idea to pass a statement result or graph data directly instead of executing a cypher statement would be great! Is there anything I can help with to get this going?

**Comment by thebestnom** [comment]
After https://github.com/neo4j-contrib/neovis.js/pull/127 you can just get `nodes` or `edges` and add nodes directly to there and it will update the vis
Adding a cypher updater will be cool, Ill add an issue for that later
Im not 100% sure adding pass driver instead of passing it would make that much of a difference, but I can add that in a different PR

**Pull request closed without merging**
